name: Run Go Script

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
# 新增步骤：设置 Go 版本
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run Go script
        run: go run main.go

      - name: Commit files
        run: bash .github/commit-script.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
